services:
    postgres:
        image: postgres
        restart: always
        shm_size: 128mb
        container_name: postgres_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: demo_dev 
        ports:
            - "5432:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data
volumes:
    pg_data:
